// SPDX-License-Identifier: MIT
// Copyright (c) 2019 Ha Thach (tinyusb.org)
// Copyright (c) 2023 Rene Wolf

#ifndef _USB_DESCRIPTORS_H
#define _USB_DESCRIPTORS_H

// Input terminal (Microphone input)
#define USB_DESCRIPTORS_ID_INPUT        0x01
// Output terminal (USB)
#define USB_DESCRIPTORS_ID_OUTPUT       0x03
// Clock Source units
#define USB_DESCRIPTORS_ID_CLOCK        0x04

// Fake signal path units
#define USB_DESCRIPTORS_ID_INPUT_20     0x11
#define USB_DESCRIPTORS_ID_INPUT_28     0x12
#define USB_DESCRIPTORS_ID_INPUT_40     0x13
#define USB_DESCRIPTORS_ID_INPUT_50     0x14

#define USB_DESCRIPTORS_ID_SELECT_CLK0  0x21
#define USB_DESCRIPTORS_ID_SELECT_CLK1  0x22

#define USB_DESCRIPTORS_ID_OUTPUT_CLK0  0x31
#define USB_DESCRIPTORS_ID_OUTPUT_CLK1  0x32


#define USB_DESCRIPTOR_SERIAL_LEN 16
void usb_descriptor_set_serial(const char* serial);

/* 4.7.2.7 Selector Unit Descriptor */
#define TUD_AUDIO_DESC_SELECTOR_UNIT_4_LEN (7+4)
#define TUD_AUDIO_DESC_SELECTOR_UNIT_4(_bUnitID, _baSourceID1, _baSourceID2, _baSourceID3, _baSourceID4, _bmControls, _iSelector) \
	TUD_AUDIO_DESC_SELECTOR_UNIT_4_LEN, \
	TUSB_DESC_CS_INTERFACE, \
	AUDIO_CS_AC_INTERFACE_SELECTOR_UNIT, \
	_bUnitID, \
	4, \
	_baSourceID1, _baSourceID2, _baSourceID3, _baSourceID4, \
	_bmControls, \
	_iSelector



#define TUD_AUDIO_DESC_CS_AC_LEN_TOTAL ( \
	TUD_AUDIO_DESC_CLK_SRC_LEN \
	+ TUD_AUDIO_DESC_INPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_OUTPUT_TERM_LEN \
	\
	+ TUD_AUDIO_DESC_INPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_INPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_INPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_INPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_SELECTOR_UNIT_4_LEN \
	+ TUD_AUDIO_DESC_SELECTOR_UNIT_4_LEN \
	+ TUD_AUDIO_DESC_OUTPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_OUTPUT_TERM_LEN \
	)

#define TUD_AUDIO_DESC_TOTAL_LEN ( \
	TUD_AUDIO_DESC_IAD_LEN \
	+ TUD_AUDIO_DESC_STD_AC_LEN \
		+ TUD_AUDIO_DESC_CS_AC_LEN \
			+ TUD_AUDIO_DESC_CS_AC_LEN_TOTAL \
		+ TUD_AUDIO_DESC_STD_AS_INT_LEN \
		+ TUD_AUDIO_DESC_STD_AS_INT_LEN \
	+ TUD_AUDIO_DESC_CS_AS_INT_LEN \
		+ TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN \
		+ TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN \
		+ TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN \
	)

#endif
